### ISSUE TITLE
Update scramble to 1.0.2 in bioconda

### ISSUE THREAD

**Issue by eudesbarbosa** [GeneDx/scramble#28]
**Issue**
We would like to include `scramble` to our MEI analysis workflow, but our workflow relies on Conda and requires VCF outputs.
The changes to fix VCF output are in `1.0.2`, but it was not integrated to `bioconda-recipes`. 

**Suggestion**
Update `bioconda-recipes`. We tried in https://github.com/bioconda/bioconda-recipes/pull/36929, but there is something missing. Perhaps version defined in `scramble/cluster_identifier/src/cluster_identifier.c` ?

**Comment by holtgrewe** [comment]
@eudesbarbosa I think that actually is the issue. I will try to patch the recipe for v1.0.2.

@CarlosBorroto Would it be possible to patch your `cluster_identifier.c` file with with appropriate version and make a v1.0.3 release? Also, is it intentional that you switched the naming scheme of tags? Anyway, thank you for the great tool scramble!

**Comment by eudesbarbosa** [comment]
Solved by https://github.com/bioconda/bioconda-recipes/pull/36969
